# MINIMAX


### Minimax es un algoritmo recursivo. John von Neumann es el creador del teorema minimax Un procedimiento recursivo y el corte de la recursión está dado por alguna de las siguientes condiciones: Gana algún jugador Se han explorado N capas, siendo N el límite establecido Se ha agotado el tiempo de exploración Se ha llegado a una situación estática donde no hay grandes cambios de un nivel a otro. 


Espacio de busqueda queda definido por:

Estado inicial: es decir estado en el que el juego inicia

Operadores: Corresponde a las jugadas legales que se pueden hacer en el juego.

Condición Terminal: Determina cuando el juego se acabó, es decir cuando unos de los dos gano.

Función de Utilidad: Da un valor numérico a una configuración final de un juego. En un juego en donde se puede ganar, perder o 
empatar, los valores pueden ser 1, 0, o -1.




## Que es Alpha-beta pruning?
La poda alfa beta es una técnica de búsqueda que reduce el número de nodos evaluados en un árbol de juego por el algoritmo Minimax. Se trata de una técnica muy utilizada en programas de juegos entre adversarios como el ajedrez, el tres en raya o el Go.



El problema de la búsqueda Minimax es que el número de estados a explorar es exponencial al número de movimientos. Partiendo de este hecho, la técnica de poda alfa-beta trata de eliminar partes grandes del árbol, aplicándolo a un árbol Minimax estándar, de forma que se devuelva el mismo movimiento que devolvería este, gracias a que la poda de dichas ramas no influye en la decisión final.

La poda alfa-beta toma dicho nombre de la utilización de dos parámetros que describen los límites sobre los valores hacia atrás que aparecen a lo largo de cada camino.

α es el valor de la mejor opción hasta el momento a lo largo del camino para MAX, esto implicará por lo tanto la elección del valor más alto*

β es el valor de la mejor opción hasta el momento a lo largo del camino para MIN, esto implicará por lo tanto la elección del valor más bajo.*


Esta búsqueda alfa-beta va actualizando el valor de los parámetros según se recorre el árbol. El método realizará la poda de las ramas restantes cuando el valor actual que se está examinando sea peor que el valor actual de α o β para MAX o MIN, respectivamente.


<img src="2.PNG">



In [2]:
from easyAI import TwoPlayersGame, Human_Player, AI_Player, Negamax
import numpy as np

In [3]:
class TresEnRaya(TwoPlayersGame):
    
    def __init__(self,nplayers):
        self.tablero = np.zeros((3,3),dtype = int)
        self.nplayer = 1
        self.mapa = {}
        cont = 1
        for i in range(len(self.tablero)):
            for j in range(len(self.tablero)):
                self.mapa[cont]=(i,j)
                cont+=1
                
        #print(self.mapa)
        self.players = nplayers
        

    def possible_moves(self):
        moves = []
        cont = 1
        for i in range(len(self.tablero)):
            for j in range(len(self.tablero)):
                if self.tablero[i][j] == 0:
                    moves.append(cont)
                cont+=1
                
        #print(moves)
        return moves
    
    def make_move(self,casillero):
        pos = self.mapa[casillero]
        self.tablero[pos[0]][pos[1]] = self.nplayer
        
    def unmake_move(self,casillero):
        pos = self.mapa[casillero]
        self.tablero[pos[0]][pos[1]] = 0
        
    def lose(self):
        for i in range(len(self.tablero)):
            if np.all(self.tablero[i,:]==self.nopponent,axis = 0) or np.all(self.tablero[:,i]==self.nopponent,axis = 0):
                return True
        
        
        if self.tablero[0][0]==self.nopponent and self.tablero[1][1]==self.nopponent and self.tablero[2][2]==self.nopponent:
            return True
        
        if self.tablero[2][0]==self.nopponent and self.tablero[1][1]==self.nopponent and self.tablero[0][2]==self.nopponent:
            return True
        
        return False
    
    
    def show(self):
        print(self.tablero)
        
        
    def scoring(self):
        return -100 if self.lose() else 0

        
    def is_over(self):
        return (self.possible_moves() == [] or self.lose())
            
    
if __name__=="__main__":
    ai_algo = Negamax(6)
    tresenraya = TresEnRaya([Human_Player(),AI_Player(ai_algo)])
    tresenraya.play()

[[0 0 0]
 [0 0 0]
 [0 0 0]]

Player 1 what do you play ? 2

Move #1: player 1 plays 2 :
[[0 1 0]
 [0 0 0]
 [0 0 0]]

Move #2: player 2 plays 1 :
[[2 1 0]
 [0 0 0]
 [0 0 0]]

Player 1 what do you play ? 3

Move #3: player 1 plays 3 :
[[2 1 1]
 [0 0 0]
 [0 0 0]]

Move #4: player 2 plays 4 :
[[2 1 1]
 [2 0 0]
 [0 0 0]]

Player 1 what do you play ? 1

Player 1 what do you play ? 3

Player 1 what do you play ? 4

Player 1 what do you play ? 5

Move #5: player 1 plays 5 :
[[2 1 1]
 [2 1 0]
 [0 0 0]]

Move #6: player 2 plays 7 :
[[2 1 1]
 [2 1 0]
 [2 0 0]]
